### ISSUE TITLE
Couldn't find resource handling

### ISSUE THREAD

**Issue by ghost** [Firecul/GTA-V-Default-Handling-Files---FiveM-resource#1]
![Udklip](https://user-images.githubusercontent.com/72620630/95606858-3f958f80-0a5b-11eb-99dd-43eacfd10b63.PNG)

**Comment by Firecul** [comment]
I haven't tried to use it for a while, I'll look into it tonight.

**Comment by Firecul** [comment]
Out of interest @ZaptorDK, what would be preferred, having the individual files or just the unified file to edit? I'd lean towards just the one.

**Comment by ghost** [comment]
> Out of interest @ZaptorDK, what would be preferred, having the individual files or just the unified file to edit? I'd lean towards just the one.

Idk. Sry.

**Comment by Firecul** [comment]
As of now it does seem to be working for me, can you try deleting the folder and adding the new cloned one @ZaptorDK? 
If that doesn't work I'll have to get you to show me your install and we can try to figure out what's wrong on your end.

**Comment by ghost** [comment]
> As of now it does seem to be working for me, can you try deleting the folder and adding the new cloned one @ZaptorDK? 
> If that doesn't work I'll have to get you to show me your install and we can try to figure out what's wrong on your end.

I'll try. Are u sure it works with vRP also?

**Comment by Firecul** [comment]
I have not tried with vRP only stock FiveM
