### ISSUE TITLE
this was in the Github archive program?

### ISSUE THREAD

**Issue by KendallDoesCoding** [Firecul/GTA-V-Default-Handling-Files---FiveM-resource#2]
HOWW

**Comment by Firecul** [comment]
I think just because it was on Github at the right time tbh

**Comment by KendallDoesCoding** [comment]
> I think just because it was on Github at the right time tbh

Oh, so they archive during the new year?

**Comment by Firecul** [comment]
I have no idea what criteria they use

**Comment by KendallDoesCoding** [comment]
> I have no idea what criteria they use

Ok, I really want the badge on my profile lol, so I'm interested.

**Comment by Firecul** [comment]
I don't think you'd be able to now, it was the 2020 project.
https://archiveprogram.github.com/arctic-vault/
> The 02/02/2020 snapshot archived in the GitHub Arctic Code Vault swept up every active public GitHub repository. It included every repo with any commits between the announcement at GitHub Universe on November 13th and 02/02/2020; every repo with at least 1 star and any commits from the year before the snapshot; and all repos with at least 250 stars. (It also included gh-pages for those repositories.) The snapshot consists of the HEAD of the default branch of each repository, minus any binaries larger than 100KB in size. (Repos with 250+ stars retained their binaries.) Each was packaged as a single TAR file.

> For greater data density and integrity, most data was stored QR-encoded, and compressed. A human-readable index and [guide](https://github.com/github/archive-program) found on every reel explains how to recover the data. The 02/02/2020 snapshot, consisting of 21TB of data, was archived to 186 reels of film by our archive partners [Piql](https://www.piql.com/) and then transported to the Arctic Code Vault, where it resides today.

**Comment by KendallDoesCoding** [comment]
> I don't think you'd be able to now, it was the 2020 project. https://archiveprogram.github.com/arctic-vault/
> 
> > The 02/02/2020 snapshot archived in the GitHub Arctic Code Vault swept up every active public GitHub repository. It included every repo with any commits between the announcement at GitHub Universe on November 13th and 02/02/2020; every repo with at least 1 star and any commits from the year before the snapshot; and all repos with at least 250 stars. (It also included gh-pages for those repositories.) The snapshot consists of the HEAD of the default branch of each repository, minus any binaries larger than 100KB in size. (Repos with 250+ stars retained their binaries.) Each was packaged as a single TAR file.
> 
> > For greater data density and integrity, most data was stored QR-encoded, and compressed. A human-readable index and [guide](https://github.com/github/archive-program) found on every reel explains how to recover the data. The 02/02/2020 snapshot, consisting of 21TB of data, was archived to 186 reels of film by our archive partners [Piql](https://www.piql.com/) and then transported to the Arctic Code Vault, where it resides today.

Oh so it's not a yearly thing? nvm then.
