### ISSUE TITLE
MP Turner downforce stats?

### ISSUE THREAD

**Issue by rooleyzee123** [Firecul/GTA-V-Default-Handling-Files---FiveM-resource#6]
unsure if there was possibly a mistake with your export of MP tuner or maybe I'm missing something here but a number of the vehicles listed have a ridiculously high downforce modifier and looks like maybe the decimal place might be missing ie with the calico rather than being 1.5 it is 150 downforce.

I'd help out with this list unsure on the best way to grab these default values.

**Comment by rooleyzee123** [comment]
Taken a look at the default files and i think I'm the one who is wrong here

**Comment by Firecul** [comment]
> Taken a look at the default files and i think I'm the one who is wrong here

Technically it's R* that is wrong lol

![image](https://user-images.githubusercontent.com/34950371/215206686-bf836046-d1ab-461b-b86a-02d6d9078761.png)

**Comment by rooleyzee123** [comment]
> > Taken a look at the default files and i think I'm the one who is wrong here
> 
> Technically it's R* that is wrong lol
> 
> ![image](https://user-images.githubusercontent.com/34950371/215206686-bf836046-d1ab-461b-b86a-02d6d9078761.png)

No idea how this is the case with what they have done here. But yeah R* are the ones here who messed up  😁
