### ISSUE TITLE
New builds

### ISSUE THREAD

**Issue by Lorenc95** [Firecul/GTA-V-Default-Handling-Files---FiveM-resource#7]
Hi there bossman!

Could u update it to include the newest build(s)?
https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build

**Comment by Firecul** [comment]
I haven't honestly tried it myself in a long time so completely forgot about that.
Should be good now with 22a7ea8 unless I missed something?

**Comment by Lorenc95** [comment]
I believe there is a new DLC though correct me if i am wrong.
2802 | mpchristmas3 | Los Santos Drug Wars
The resource update -> fxmanifest is a good one indeed.
as it could have resolved some issues.

**Comment by Firecul** [comment]
> 2802 | mpchristmas3 | Los Santos Drug Wars 

Already added back in December ;)
572e991a60c6b3f3171ab70d620541f9f3da5217

**Comment by Lorenc95** [comment]
My bad then u can close it hehe!

Op zo 26 mrt. 2023 20:02 schreef Firecul ***@***.***>:

**Comment by Firecul** [comment]
No problem, always good someone checks and reminds me on missing things.
